name: ubuntu

on: 
    workflow_dispatch:
    schedule:
    # * is a special character in YAML so you have to quote this string
    # https://docs.github.com/cn/actions/reference/events-that-trigger-workflows#scheduled-events
      - cron:  '0 0 * * 5'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        algorithms: [pytest]
    steps:
    - uses: actions/checkout@v2
    - uses: snickerbockers/submodules-init@v4
    - uses: actions/cache@v2
      with:
        path: |
          /*
        key: ${{ runner.os }}-x86-x64-${{ matrix.algorithms }}
    - name: test algorithm
      working-directory: ${{github.workspace}}
      run: |
        pip install pytest
        pytest
